### ISSUE TITLE
Update the code to use the new Optim.jl interface

### ISSUE THREAD

**Issue by juliohm** [juliohm/Variography.jl#2]
As discussed in #1

**Comment by pkofod** [comment]
Do tell me if you need any assistance!

**Comment by juliohm** [comment]
Thank you @pkofod, that would be very helpful. :) I'd be happy to merge a PR with a new tag for Optim.jl in the REQUIRE if you have time. The new documentation looks great BTW.

**Comment by juliohm** [comment]
Fixed by #3
