### ISSUE TITLE
EmpiricalVariogram for large datasets

### ISSUE THREAD

**Issue by mateuszbaran** [juliohm/Variography.jl#6]
First, thanks for a nice package!

Would you consider changing the inner constructor of `EmpiricalVariogram` so that it can calculate `ordinate` and `counts` without preallocating `lags` and `zdiff` (controlled by a keyword argument)? I have a relatively large dataset (about 100000 points in a regular grid) and the current method results in out-of-memory errors for me. I can make a PR if you think this is OK.

**Comment by mateuszbaran** [comment]
No, actually I mean not allocating these two arrays at all. I've sketched an implementation here:

```julia

function empirical_variogram(X, z₁, z₂, nlags, maxlag = nothing, distance = Euclidean())
    # sanity checks
    @assert nlags > 0 "number of lags must be positive"
    if maxlag ≠ nothing
        @assert maxlag > 0 "maximum lag distance must be positive"
    end

    # number of point pairs
    npoints = size(X, 2)
    npairs = (npoints * (npoints-1)) ÷ 2

    if maxlag === nothing
        maxlag = 0.0
        for j=1:npoints
            xj = view(X,:,j)
            for i=j+1:npoints
                xi = view(X,:,i)
                δx = evaluate(distance, xi, xj)
                maxlag = max(maxlag, δx/2)
            end
        end
    end

    # corresponding bin size
    binsize = maxlag / nlags

    # variogram abscissa
    abscissa = range(binsize/2, stop=maxlag - binsize/2, length=nlags)

    binsums = fill(0.0, nlags)
    bincounts = fill(0, nlags)

    anyvalid = false
    for j=1:npoints
        xj = view(X,:,j)
        for i=j+1:npoints
            xi = view(X,:,i)
            δx = evaluate(distance, xi, xj)
            δz = (z₁[i] - z₁[j])*(z₂[i] - z₂[j])
            if !isnan(δz)
                anyvalid = true
                binidx  = ceil.(Int, δx / binsize)

                if binidx ≤ nlags
                    binsums[binidx] += δz
                    bincounts[binidx] += 1
                end
            end
        end
    end

    if anyvalid
        ordinate = [bincounts[i] > 0 ? binsums[i]/(2*bincounts[i]) : NaN for i in 1:nlags]

        return (abscissa, ordinate, bincounts)
    else
        return (abscissa, fill(NaN, nlags), fill(0, nlags))
    end
end
```

It's definitely not optimal and for some distances it could be much faster but this at least uses reasonable amounts of memory.

**Comment by juliohm** [comment]
The only thing that I don't like scanning the code quickly is that you are computing the distances twice in two loops when maxlag is not provided. Maybe there is a way to refactor the code to avoid this recalculation? I like the idea of saving memory. Let's brainstorm more this improvement. Also make sure that we don't change the behavior when some arguments are not specified by the user. Thanks for taking a look into this.

**Comment by juliohm** [comment]
One thing that I am starting to consider is refactor the code so that EmpiricalVariogram constructor takes spatial data types as input. Then the case with raw matrices `X` and vectors `z1` and `z2` would be just a method that wraps the arrays into a `PointSetData` and then calls the main constructor. This way we can do further optimizations when for example the type is a `RegularGridData` type. The default maxlag is computed in constant time for example.

**Comment by mateuszbaran** [comment]
I don't really like calculating distances twice either but they are needed to calculate `binsize` that is needed since the first iteration of the loop that fills `binsums` and `bincounts`. They can't be cached either because it takes too much memory. But I like the idea of computing `maxlag` faster for `RegularGridData`.

**Comment by juliohm** [comment]
Thank you @mateuszbaran for pointing out this issue. It is now fixed in master as we discussed. The new implementation should be much more efficient in terms of memory. Also, if you use GeoStats.jl data types (e.g. RegularGridData) you will get more efficient code.

**Comment by mateuszbaran** [comment]
Thank you, it works very well now :slightly_smiling_face: .
